version: '3.3'

services:
  postgres:
    image: 'postgres:15'
    container_name: container_uniondb
    restart: always
    environment:
      - POSTGRES_DB=uniondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=43803168cacharifc
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4'
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80


